# Generated by Django 4.0.2 on 2022-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='src',
            field=models.CharField(default='', max_length=200),
        ),
    ]
